# Generated by Django 4.0.5 on 2023-11-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0002_section_num_class_in_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='uid',
            field=models.CharField(max_length=8),
        ),
    ]
